{
	"version": 1726328657,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/solidtile.png",
		"images/movingsolidtile.png",
		"images/jumpthrutile.png",
		"images/sprite-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/tiledbackground2.png",
		"images/spritefont.png",
		"images/sprite7-sheet0.png",
		"images/rat-sheet0.png",
		"images/rat-sheet1.png",
		"images/invisible1-sheet0.png",
		"images/heartreal-sheet0.png",
		"images/roadblock.png",
		"images/roadblock1-sheet0.png",
		"images/stopsign-sheet0.png",
		"images/pole-sheet0.png",
		"images/drone-sheet0.png",
		"images/drone-sheet1.png",
		"images/arrow-sheet0.png",
		"images/spike-sheet0.png",
		"media/collect 8 bit sfx.m4a",
		"media/collect 8 bit sfx.ogg",
		"media/falling 8 bit sfx.m4a",
		"media/falling 8 bit sfx.ogg",
		"media/jump 8 bit sfx.m4a",
		"media/jump 8 bit sfx.ogg",
		"media/rat death 8 bit sfx.m4a",
		"media/rat death 8 bit sfx.ogg",
		"media/victory 8 bit sfx.m4a",
		"media/victory 8 bit sfx.ogg",
		"media/hurt 8 bit sfx.m4a",
		"media/hurt 8 bit sfx.ogg",
		"media/defeat 8 bit sfx.m4a",
		"media/defeat 8 bit sfx.ogg",
		"media/nintendo 3ds music  mii maker (quieter).m4a",
		"media/nintendo 3ds music  mii maker (quieter).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}